Repository ucsb-cs156-s22/s22-5pm-courses, pull requests merged in 2022-06, with the labels that each got.

#44 s22-5pm-2 jj Removed addedCourses list from PersonalSchedule entity
  src/main/java/edu/ucsb/cs156/courses/entities/PersonalSchedule.java
Labels: s22-5pm-2

#26 s22-5pm-2 hkk - added Edit for personal schedule & tests
  frontend/src/App.js
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
  frontend/src/main/components/PersonalSchedules/PersonalSchedulesTable.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesEditPage.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesEditPage.test.js
Labels: s22-5pm-2, :+1: Merge Candidate, :gear: Deploying on QA

#41 s22-5pm-1 Nga Alex Xiangqi Chris - Added section search to nav bar and tests
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/SectionSearch/SectionSearchIndexPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/SectionSearch/SectionSearchIndexPage.test.js
Labels: 10, s22-5pm-1

#49 s22-5pm-1 cs - changed app title and added calendar favicon
  frontend/public/favicon.ico
  frontend/public/index.html
Labels: s22-5pm-1, :+1: Peer-cr-done

#57 s22-5pm-1 cs - changes navbar color to UCSB blue
  frontend/src/index.css
Labels: s22-5pm-1, :+1: Peer-cr-done

#53 s22-5pm-1 Section Search Drop Down Search
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/pages/SectionSearch/SectionSearchIndexPage.js
  frontend/src/stories/components/Sections/SectionsTable.stories.js
  frontend/src/stories/pages/HomePage/SectionSearch/SectionSearchIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
  frontend/src/tests/pages/SectionSearch/SectionSearchIndexPage.test.js
Labels: s22-5pm-1, :+1: Peer-cr-done, :gear: Deploying on QA

#60 s22-5pm-1 Implemented Sections Search Table
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/stories/components/Sections/SectionsTable.stories.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: s22-5pm-1, :+1: Peer-cr-done

#34 s22-5pm-2 Limin Ding - add_post_api_coursesadded
  .github/workflows/34-frontend-mutation-testing.yml
  src/main/java/edu/ucsb/cs156/courses/controllers/AddedCoursesController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/AddedCoursesControllerTests.java
Labels: s22-5pm-2, 10

#58 s22-5pm-1 Table formatting
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/pages/SectionSearch/SectionSearchIndexPage.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: s22-5pm-1, :+1: Peer-cr-done

#64 s22-5pm-1 Adding section number to table
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/utils/sectionUtils.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
  frontend/src/tests/utils/sectionUtils.test.js
Labels: s22-5pm-1, :+1: Peer-cr-done

#43 s22-5pm-2 - Added details button to Personal Schedule Table + tests
  frontend/src/main/components/PersonalSchedules/PersonalSchedulesTable.js
  frontend/src/tests/components/PersonalSchedules/PersonalSchedulesTable.test.js
Labels: s22-5pm-2, 10, :+1: Merge Candidate, :+1: Peer-cr-done, :hourglass_flowing_sand: Waiting on CI/CD to merge

#65 s22-5pm-1 format enrollment
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/utils/sectionUtils.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
  frontend/src/tests/utils/sectionUtils.test.js
Labels: s22-5pm-1, :+1: Peer-cr-done

#63 S22-5pm-2 RV - Add API endpoint for getting section information from a schedule
  src/main/java/edu/ucsb/cs156/courses/controllers/AddedCoursesController.java
  src/main/java/edu/ucsb/cs156/courses/documents/Course.java
  src/main/java/edu/ucsb/cs156/courses/documents/CoursePage.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/AddedCoursesControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: s22-5pm-2, 10, :+1: Merge Candidate, :+1: Peer-cr-done, :hourglass_flowing_sand: Waiting on CI/CD to merge
