Repository ucsb-cs156-s22/s22-5pm-courses, pull requests merged in 2022-05, with the labels that each got.

#13 5pm-1 Added herokuqa link to readme
  README.md
Labels: s22-5pm-1

#12 5pm-2 ap - added Heroku qa linkto README.md
  README.md
Labels: s22-5pm-2, 5

#7 5pm-2 hkk - added Heroku production app and dashboard links to README.md
  README.md
Labels: s22-5pm-2, 10, Merge Candidate

#23 s22-5pm-2 jj - Section Info Service Function
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: s22-5pm-2, 10

#32 s22-5pm-2 - Added Storybook QA and Production links to README.md
  README.md
Labels: s22-5pm-2

#31 s22-5pm-2 RV - add more stories to nav bar
  frontend/src/stories/components/Nav/AppNavbar.stories.js
Labels: s22-5pm-2, :+1: Peer-cr-done

#27 s22-5pm-2 hkk - created a placeholder page for personal schedule detail page
  frontend/src/App.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesDetailPage.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesDetailPage.test.js
Labels: s22-5pm-2, 10

#36 s22-5pm-1 cs - fix frontend tests so that red error blocks do not show
  frontend/src/tests/components/BasicCourseSearch/BasicCourseSearchForm.test.js
  frontend/src/tests/components/Subjects/SingleSubjectDropdown.test.js
  frontend/src/tests/pages/HomePage.test.js
Labels: 5, s22-5pm-1
